# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: notedown
#email: hatappo44__at__gmail__dot__com
description: > # this means to ignore newlines until "baseurl:"
  Notes, links and a few blogs about system development.
baseurl: "/notedown" # the subpath of your site, e.g. /blog
url: "http://hatappo.github.io/notedown/" # the base hostname & protocol for your site
twitter_username: hatappo
github_username:  hatappo

# Build settings
markdown: kramdown

#timezone: Japan/Tokyo
permalink: none


# My settings
repository_url: https://github.com/hatappo/notedown
